### ISSUE TITLE
new feature for fail over

### ISSUE THREAD

**Issue by johnykov** [softwaremill/slick-eventsourcing#5]
Actually, one more thought: maybe it would make more sense to fail over using events between a range of IDs? The ids are time-based so it's quite easy to generate an ID corresponding to a given timestamp (maybe we'd need to extend the id-generator for that).

Two use cases here:
- restore the system as it was at a given time
- having a model with all events up to X applied, apply the new events (after X)

Also, id is the primary key so automatically indexed, that will behave better then a query on the date

**Comment by johnykov** [comment]
External dependency is already prepared https://github.com/softwaremill/scala-common/commit/9de40881c8

**Comment by adamw** [comment]
Sure, sounds useful :) One thing to watch out for is making sure we only apply whole transactions (events with the same txid field); on date boundaries we may get a partial transaction in some cases

In fact, we applying the events it would probably make sense to group them into transactions and apply all events from a single tx in one tx? But that's another issue I suppose

**Comment by johnykov** [comment]
done with #6
